# ===============================================================================================================
# Create a phyloseq object out of dietary and tree data and run ordination.
# Add metadata (GLU_index) before making a phyloseq object.
# Version 2
# Created on 09/09/2022 by Rie Sadohara
# ===============================================================================================================

# Set your working directory to the main directory.
  Session --> Set working directory --> Choose directory.
  setwd("~/GitHub/dietary_patterns")

# Name your main directory for future use. 
  main_wd <- file.path(getwd())

# ---------------------------------------------------------------------------------------------------------------
# Install BiocManager in order to install the "phyloseq" package.
  if (!require("BiocManager", quietly = TRUE))install.packages("BiocManager")

# Install the phyloseq package if you have not done so.
  # BiocManager::install("phyloseq")
# ---------------------------------------------------------------------------------------------------------------

# load the necessary packages and source code.
  library(phyloseq)
  library(ggplot2)
  library(ggtree)
  library(SASxport)
  source("lib/unifrac_ordination.R")
  source("lib/specify_data_dir.R")
  source("lib/ggplot2themes.R")

# Load the distinct 100 colors for use.   
  distinct100colors <- readRDS("~/GitHub/R_Toolbox/distinct100colors.rda")

# You can come back to the main directory by:
  setwd(main_wd)

# Set working directory.
  SpecifyDataDirectory("eg_data/NHANES/Laboratory_data/")

# ===============================================================================================================
# Generate a phyloseq object using food, taxonomy, tree, and sample (metadata) for ordination. 
# ===============================================================================================================
  
# Load the necessary files for creating a phyloseq object.  
  
# Food
  # Load food OTU table - this is our food OTU data
  food <- read.delim("Foodtree/Food_D12_FC_cc_f_males50s_red_Lv4.dhydrt.otu.txt", row.names=1)
  
  # Format the food file and create a otu_table called OTU.
  PrepFood(data=food)
  
  # Take a look at the food file.
  # The column name of "food" is SEQN preceded with an 'X'.
  food[1:8, 1:8]
  
# Taxonomy (tax)
  # Load taxonomy file generated by the MakeFoodTree function.   
  tax <- read.delim("Foodtree/Food_D12_FC_cc_f_males50s_red_Lv4.taxonomy.txt")
  
  # Format the tax file and create a taxonomy table called TAX.
  PrepTax(data=tax)
  
# Sample
  # Load the demographics data.
  demog <- read.xport("../Raw_data/DEMO_I.XPT")

  # Load a dataset that has the "GLU_index" information. 
  glu <- read.delim( file="QCtotal_d_glu_body_meta.txt", sep= "\t", header= T )
  
  # Take out only the SEQN and GLU_index.
  SEQN_GLU <- glu[, c("SEQN", "GLU_index")]
  
  # Add GLU_index to metadata. 
  demog_glu <- merge(x=SEQN_GLU, y=demog, all.x=TRUE, by="SEQN")
  
  # Now, it has GLU_index.
  head(demog_glu, 2)
  
  # Put 'X' in front of the SEQN and define it as rownames.    
  rownames(demog_glu) <- paste("X", demog_glu$SEQN, sep="") 
  
  # Prep metadata for generating a phyloseq object.  
  PrepMeta_NHANES(data= demog_glu)
  
# Food tree
  # Load foodtree file generated by the MakeFoodTree function.   
  foodtree <- read_tree("Foodtree/Food_D12_FC_cc_f_males50s_red_Lv4.nwk")
  # It is OK to see a message that says:
  # "Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
  # Also defined by 'tidytree'"
  
  # Format the food tree and save it as 'TREE'. 
  PrepTree(data=foodtree)
  # It is OK to see the same message as the previous line. 
  
# ---------------------------------------------------------------------------------------------------------------
# Make a phyloseq object with OTU, TAX, samples, and foodtree by using the phyloseq function.
  phyfoods <- phyloseq(OTU, TAX, SAMPLES, TREE)
  # It is OK to see the same message as the previous line. 
  
# Check your metadata
# Show the sample names. Change n to adjust the number of rows to show.
  head(sample_names(phyfoods), n=6)  
  
# Show metadata. 
  head(sample_data(phyfoods), n=2)
  
# Show only the columns (variables) of metadata. 
  sample_variables(phyfoods)
  
# Check the level 1 foods in your food tree 
  L1s <- tax_table(phyfoods)[, "L1"]
  as.vector(unique(L1s))

# Change to the folder called "Ordination" in your "Ordination" folder.
  SpecifyDataDirectory(directory.name = "eg_data/NHANES/Laboratory_data/Ordination/")

# ===============================================================================================================
# Use your phyloseq object and perform ordination - WEIGHTED unifrac distance
# ===============================================================================================================
  
# Perform Principal Coordinate Analysis (PCoA) with WEIGHTED unifrac distance of your food data.
  # This may take a few minutes depending on your data size.
  # e.g. a large phyloseq object (7.9 MB) could take a few minutes.
  ordinated_w <- phyloseq::ordinate(phyfoods, method="PCoA", distance="unifrac", weighted=TRUE) 

# Save the percent variance explained by the axes as a vector to use in plots.  
  eigen_percent_w <- ordinated_w$values$Relative_eig
  
# Save the percent variance explained as a txt file.
  Eigen(eigen.input = eigen_percent_w, 
        output.fn="Food_D12_FC_cc_f_males50s_red_Lv4_ord_WEIGHTED_eigen.txt")

  
# ===============================================================================================================
# Plot your ordination results - WEIGHTED
# ===============================================================================================================
  
# Merge the first n axes to the metadata and save it as a txt file. 
# The merged dataframe, 'meta_usersdf', will be used for plotting.
  MergeAxesAndMetadata_NHANES(ord.object= ordinated_w, number.of.axes= 10, meta.data= demog_glu, 
                              output.fn= "Food_D12_FC_cc_f_males50s_red_Lv4_ord_WEIGHTED_meta_users.txt")

# Load the output again for plotting.
  loaded_glu_w <- read.table("Food_D12_FC_cc_f_males50s_red_Lv4_ord_WEIGHTED_meta_users.txt",
                             sep="\t", header=T)
  
# Convert the GLU_index as a factor to plot it in order.
  loaded_glu_w$GLU_index <- factor(loaded_glu_w$GLU_index, labels= c("Normal", "Prediabetic", "Diabetic"))

# ---------------------------------------------------------------------------------------------------------------
# Plot Axis 1 and Axis 2 to show the separation of samples colored by Groups as in the metadata.
  p1_w <- ggplot(loaded_glu_w, aes(x=Axis.1, y=Axis.2, color=GLU_index)) +
    geom_point(aes(color= GLU_index), size=3) + 
    scale_color_manual( values= c("turquoise2", "goldenrod3", "mediumvioletred")) +
    xlab( paste("Axis.1 (", paste(round(eigen_percent_w[1]*100, 1)), "%)", sep="") ) +
    ylab( paste("Axis.2 (", paste(round(eigen_percent_w[2]*100, 1)), "%)", sep="") ) +
    no_grid + space_axes + theme(aspect.ratio = 1)
  p1_w
  
# Save p1 as a PDF. 
  ggsave("Food_D12_FC_cc_f_males50s_red_Lv4_ord_WEIGHTED_Axis12_p1.pdf", 
         p1_w, device="pdf", width=7, height=5.5, unit="in", dpi=300)
  
# You can add ellipses at a desired confidence level; but with this 
# example data, there are too few samples per user to draw them. 
  ellipses_w <- p1_w + stat_ellipse(level=0.95) 
  ellipses_w
  
# Save ellipses as a PDF. 
  ggsave("Food_D12_FC_cc_f_males50s_red_Lv4_ord_WEIGHTED_Axis12_ellipses.pdf", 
         ellipses_w, device="pdf", width=7, height=5.5, unit="in", dpi=300)

# ---------------------------------------------------------------------------------------------------------------
# The GLU_index groups look different. Use beta-diversity and adonis tests to see
# if they are they actually distinct from one another.

# Generate a weighted unifrac distance matrix.
  dist_matrix_w <- phyloseq::distance(phyfoods, method = "wunifrac") # weighted
  
# Dispersion test and plot
# vegan::betadisper computes centeroids and distance of each datapoint from it. 
  dispr_w <- vegan::betadisper(d=dist_matrix_w, phyloseq::sample_data(phyfoods)$GLU_index)

# Can show the centroids and dispersion of each group. 
  plot(dispr_w)
  
# Or show the distance to centroid of each datapoint.
  boxplot(dispr_w, xlab = "")
  
# Use dispr to do a permutation test for homogeneity of multivariate dispersion
  vegan::permutest(dispr_w)
  
  # The results will be slightly different because this is a permutation-based test, 
  # which conducts 999 permutation tests by default.  
  # p-values are ~0.09-0.12, so, not significant. That means the dispersion of each group 
  # is not different. Thus, the assumption of homogeneity of dispersion is met.  
  # If it is significant, add pairwise=T argument and see which combination(s) are 
  # significantly different.
  
  # Use adonis to test whether there is a difference between groups' composition. 
  # i.e., composition among groups (food they consumed) is similar or not.
  vegan::adonis(dist_matrix_w ~ phyloseq::sample_data(phyfoods)$GLU_index) 
  # p ~ 0.6. They are not different.  
  

# ===============================================================================================================
# Use your phyloseq object and perform ordination - UNweighted
# ===============================================================================================================
  
# Perform Principal Coordinate Analysis (PCoA) with UNweighted unifrac distance of your food data.
# This may take a few minutes depending on your data size.
# e.g. a large phyloseq object (7.9 MB) takes ~ 1 min. 
  ordinated_u <- phyloseq::ordinate(phyfoods, method="PCoA", distance="unifrac", weighted=FALSE) 
  
# Save the percent variance explained by the axes as a vector to use in plots.  
  eigen_percent_u <- ordinated_u$values$Relative_eig
  
# Save the percent variance explained as a txt file.
  Eigen(eigen.input = eigen_percent_u, 
        output.fn="Food_D12_FC_cc_f_males50s_red_Lv4_ord_UNweighted_eigen.txt")
  
# ===============================================================================================================
# Plot your ordination results - UNweighted. 
# ===============================================================================================================

# Merge the first n axes to the metadata and save it as a txt file. 
# The merged dataframe, 'meta_usersdf', will be used for plotting.
  MergeAxesAndMetadata_NHANES(ord.object= ordinated_u, number.of.axes= 10, meta.data= demog_glu, 
                              output.fn= "Food_D12_FC_cc_f_males50s_red_Lv4_ord_UNweighted_meta_users.txt")
  
# Load the output again for plotting.
  loaded_glu_u <- read.table("Food_D12_FC_cc_f_males50s_red_Lv4_ord_UNweighted_meta_users.txt",
                             sep="\t", header=T)  
  
# Convert the GLU_index as a factor to plot it in order.
  loaded_glu_u$GLU_index <- factor(loaded_glu_u$GLU_index, labels= c("Normal", "Prediabetic", "Diabetic"))

# Take a look at meta_usersdf_loaded. 
  head(loaded_glu_u, 2)
  
# ---------------------------------------------------------------------------------------------------------------
# Plot Axis 1 and Axis 2 to show the separation of samples colored by Groups as in the metadata.
  p1_u <- ggplot(loaded_glu_u, aes(x=Axis.1, y=Axis.2, color=GLU_index)) +
      geom_point(aes(color= GLU_index), size=3) + 
      scale_color_manual( values= c("turquoise2", "goldenrod3", "mediumvioletred") ) +
      xlab( paste("Axis.1 (", paste(round(eigen_percent_u[1]*100, 1)), "%)", sep="") ) +
      ylab( paste("Axis.2 (", paste(round(eigen_percent_u[2]*100, 1)), "%)", sep="") ) +
      no_grid + space_axes + theme(aspect.ratio = 1)
  p1_u
  
# Save p1 as a PDF. 
  ggsave("Food_D12_FC_cc_f_males50s_red_Lv4_ord_UNweighted_Axis12_p1.pdf", 
         p1_u, device="pdf", width=7, height=5.5, unit="in", dpi=300)
  
# You can add ellipses at a desired confidence level; but with this 
# example data, there are too few samples per user to draw them. 
  ellipses_u <- p1_u + stat_ellipse(level=0.95) 
  ellipses_u
  
# Save ellipses as a PDF. 
  ggsave("Food_D12_FC_cc_f_males50s_red_Lv4_ord_UNweighted_Axis12_ellipses.pdf", 
         ellipses_u, device="pdf", width=7, height=5.5, unit="in", dpi=300)

# ---------------------------------------------------------------------------------------------------------------
# Use beta-diversity and adonis tests to see if they are they actually distinct from one another.

# Generate an UNweighted unifrac distance matrix.
  dist_matrix_u <- phyloseq::distance(phyfoods, method="unifrac")  # UNweighted 
  
# Dispersion test and plot
  # vegan::betadisper computes centeroids and distance of each datapoint from it. 
  dispr_u <- vegan::betadisper(dist_matrix_u, phyloseq::sample_data(phyfoods)$GLU_index)
  
  # Can show the centroids and dispersion of each group. 
  plot(dispr_u)
  
  # Or show the distance to centroid of each datapoint
  boxplot(dispr_u, xlab = "")
  
# Use dispr to do a permutation test for homogeneity of multivariate dispersion.
  vegan::permutest(dispr_u)
  
  # The results will be slightly different because this is a permutation-based test, 
  # which conducts 999 permutation tests by default.  
  # p-values are ~0.2, so, not significant. That means dispersion of the groups is not different.
  # Thus, the assumption of homogeneity of dispersion is met.
  # If it is significant, add pairwise=T argument and see which combination(s) are 
  # significantly different.
  
# Use adonis to test whether there is a difference between groups' composition. 
  # i.e., composition among groups (food they consumed) is similar or not.
  vegan::adonis(dist_matrix_u ~ phyloseq::sample_data(phyfoods)$GLU_index) 
  # p ~ 0.11. They are not different.  
  


# ===============================================================================================================
# Save unifrac distance (UNweighted or WEIGHTED) matrices. 
# ===============================================================================================================

# Generate and save an WEIGHTED unifrac distance matrix of "Samples". 
  WeightedUnifracDis(input.phyloseq.obj = phyfoods, 
                     output.fn = "Food_D12_FC_cc_f_males50s_red_Lv4_ord_WEIGHTED_uni_dis.txt")        

# ---------------------------------------------------------------------------------------------------------------
# Generate and save an UNweighted unifrac distance matrix of "Samples". 
  UnweightedUnifracDis(input.phyloseq.obj = phyfoods, 
                       output.fn = "Food_D12_FC_cc_f_males50s_red_Lv4_ord_UNweighted_uni_dis.txt")        
  
# ---------------------------------------------------------------------------------------------------------------
# Come back to the main directory.
  setwd(main_wd)  
  
