# ===============================================================================================================
# Create a phyloseq object out of dietary and tree data and run ordination. Food tree level = 3
# Version 1
# Created on 01/31/2023 by Rie Sadohara
# ===============================================================================================================

# Set your working directory to the main directory.
  Session --> Set working directory --> Choose directory.
  setwd("~/GitHub/DietR")

# Name your main directory for future use. 
  main_wd <- file.path(getwd())

# ---------------------------------------------------------------------------------------------------------------
# Install the BiocManager package necessary for installing the phyloseq package. 
  if (!require("BiocManager",    quietly = TRUE))install.packages("BiocManager")
# Install the phyloseq package if you have not done so.
  BiocManager::install("phyloseq")
  
# Install the devtools package necessary for installing the pairwiseAdonis package. 
  if (!require("devtools",    quietly = TRUE))install.packages("devtools")
# install pairwise adonis function from Github. (https://github.com/pmartinezarbizu/pairwiseAdonis)
  devtools::install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
  
# ---------------------------------------------------------------------------------------------------------------
# load the necessary packages and the source code.
  library(vegan)
  library(phyloseq)
  library(ggplot2)
  library(ggtree) # Shows how to cite the ggtree package. Make sure to cite it accordingly.
  library(SASxport)
  library(cluster) # necessary to the "pairwiseAdonis" package.
  library(pairwiseAdonis)
  source("lib/specify_data_dir.R")
  source("lib/ordination.R")
  source("lib/ggplot2themes.R")
  source("lib/plot.axis.1to4.by.factor.R")

# Load the distinct 100 colors for use.   
  distinct100colors <- readRDS("lib/distinct100colors.rda")

# You can come back to the main directory by:
  setwd(main_wd)

# Set working directory.
  SpecifyDataDirectory("eg_data/NHANES/PF/")

# ===============================================================================================================
# Generate a phyloseq object using food, taxonomy, tree, and sample (metadata) for ordination. 
# ===============================================================================================================
  
  ###### Let's continue to ordination ########################
### Food -----------------------------------------------------------
  # Load food OTU table in Foodtree folder - this is our food OTU data.
  food_raw <- read.delim("Foodtree/Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv.food.otu.txt", row.names=1)
  
  # Define the taxonomy column number, which is at the end of food.
  taxonomycolumn <- length(colnames(food_raw))
  
  # Order the column names of food (which is SEQN), except the last column which has taxonomy.
  sortedcolnames_order <- order(colnames(food_raw)[ 1 : taxonomycolumn-1 ])
  
  # Sort the SEQNs, but do not touch the taxonomy column at the end. 
  food <- food_raw[, c(sortedcolnames_order, taxonomycolumn) ] 
  
  # Can save this as .txt for corr.axis.foods...
  write.table(food, "Foodtree/Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv.food.otu_sortedbysample.txt",
              sep="\t", row.names=T, quote=F)
  
  # Take a look at the food file.
  # The column name of "food" is the ordered SEQNs preceded with an 'X'.
  food[1:8, 1:8] 
  
  # Format the food file and create an otu_table called OTU.
  PrepFood(data=food)
  
### Taxonomy (tax) -----------------------------------------------------------
  # Load taxonomy file generated by the MakeFoodTree function.
  tax <- read.delim("Foodtree/Food_D12_FC_QC_demo_QCed_Leg_morethanone_prep_red_3Lv.tax.txt")
  # 58 x 3.
  
  # Format the tax file and create a taxonomy table called TAX.
  PrepTax(data=tax)
  
### Sample -----------------------------------------------------------
  # Load the demographics data.
  demog <- read.xport("../Raw_data/DEMO_I.XPT")  
  
  # Load our dataset that has the "LegGroup" information.
  leg <- read.delim( file="../Total_D12_FC_QC_mean_QC_demo_ga_body_meta_Leg.txt", sep= "\t", header= T )
  table(leg$LegGroup)
  
  # Take out only the SEQN and LegGroup.
  SEQN_LEG <- leg[, c("SEQN", "LegGroup")]
  
  # Add LegGroup to metadata.
  demog_leg <- merge(x=SEQN_LEG, y=demog, all.x=T, by="SEQN")
  
  # Now, it has LegGroup and demographic data of all the 4207 people.
  head(demog_leg, 1)
  
  # # Put 'X' in front of the SEQN and define it as rownames.    
  # rownames(demog_leg) <- paste("X", demog_leg$SEQN, sep="") 
  # 
  # # Prep metadata for generating a phyloseq object.  
  # PrepMeta_NHANES(data = demog_leg)
  # 
  # 
  # demog_leg has all 4207 people, but I think it needs to have the same number of people
  # as food does (704 people).
  
  # Load a dataset that contains the 703 people and their SEQN.
  all.food.record_leg <- read.delim("Food_D12_FC_QC_demo_QCed_leg.txt")

  # From demog_leg, select only the 703 individuals who consumed legume-containing foods which are in all.food.record_leg.  
  demog_leg_red <- demog_leg[demog_leg$SEQN %in% unique(all.food.record_leg$SEQN),  ] 
  
  # Ensure the correct number of SEQNs were selected: n=703.
  length(unique(demog_leg_red$SEQN))
  
  # Put 'X' in front of the SEQN and define it as rownames.    
  rownames(demog_leg_red) <- paste("X", demog_leg_red$SEQN, sep="") 
  
  # Prep metadata for generating a phyloseq object.  
  PrepMeta_NHANES(data = demog_leg_red)
  
  # Food tree -----------------------------------------------------------
  # Load foodtree file generated by the MakeFoodTree function.
  foodtree <- read_tree("Foodtree/Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv.nwk")
  # It is OK to see a message that says:
  # "Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
  # Also defined by 'tidytree'"
  
  # Format the food tree and save it as 'TREE'. 
  PrepTree(data=foodtree)
  # It is OK to see the same message as the previous line. 
  
# ---------------------------------------------------------------------------------------------------------------
# Make a phyloseq object with OTU, TAX, samples, and foodtree by using the phyloseq function.
  phyfoods <- phyloseq(OTU, TAX, SAMPLES, TREE)
  # It is OK to see the same message as the previous line. They may appear multiple times. 
  
  # View the content of the phyfoods object. There should be 58 taxa (foods), 703 samples (people), 
  # 48 sample variabbles, 5 taxonomic ranks, and 21 internal nodes. 
  phyfoods
  
  # Check your metadata by using the functions in the phyloseq package.
  # Show the sample names. Change n to adjust the number of rows to show.
  head(sample_names(phyfoods), n=6)  
  length(sample_names(phyfoods))
  
  # Show their metadata. 
  head(sample_data(phyfoods), 6)[, 1:2]
  table(sample_data(phyfoods)[, "LegGroup"], useNA="ifany") 
  # Leg1 Leg2 Leg3 
  # 144  246  313 
  
  # Show only the columns (variables) of metadata. 
  sample_variables(phyfoods)
  
  # Check the level 1 foods in your food tree 
  L1s <- tax_table(phyfoods)[, "L1"]
  as.vector(unique(L1s))
  
  # Change to the folder called "Ordination" in your "Ordination" folder.
  SpecifyDataDirectory(directory.name = "eg_data/NHANES/PF/Ordination/")
  

  ## From here, use 55_PF_Pulses_NHANES_ord_subsample.R script to build a phyloseq object and do ordination.

  
# ===============================================================================================================
# Use your phyloseq object and perform ordination - WEIGHTED unifrac distance
# ===============================================================================================================
  
# Perform Principal Coordinate Analysis (PCoA) with WEIGHTED unifrac distance of your food data.
  # This may take a few minutes depending on your data size.
  # e.g. a large phyloseq object (7.9 MB) could take a few minutes.
  ordinated_w <- phyloseq::ordinate(phyfoods, method="PCoA", distance="unifrac", weighted=TRUE) 

# A warning message may appear saying:  
  # Warning message:
  #   In matrix(tree$edge[order(tree$edge[, 1]), ][, 2], byrow = TRUE,  :
  #               data length [1483] is not a sub-multiple or multiple of the number of rows [742]
# This warns that the food tree we are using is not bifurcating. But it is OK, since we do not 
# expect our food trees to be bifurcating.
         
# Save the percent variance explained by the axes as a vector to use in plots.  
  eigen_percent_w <- ordinated_w$values$Relative_eig
  
# Save the percent variance explained as a txt file.
  Eigen(eigen.input = eigen_percent_w, 
        output.fn="Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_WEIGHTED_eigen.txt")

  
# ===============================================================================================================
# Plot your ordination results - WEIGHTED
# ===============================================================================================================
  
# Merge the first n axes to the metadata and save it as a txt file. 
# The merged dataframe, 'meta_usersdf', will be used for plotting.
  MergeAxesAndMetadata_NHANES(ord.object= ordinated_w, number.of.axes= 10, meta.data= demog_leg_red, 
                              output.fn= "Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_WEIGHTED_meta_users.txt")
  
# Load the output again for plotting.
  loaded_leg_w <- read.table("Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_WEIGHTED_meta_users.txt",
                             sep="\t", header=T)
  
# Convert the loaded_leg_w$LegGroup as a factor to plot it in order.
  loaded_leg_w$LegGroup <- factor(loaded_leg_w$LegGroup, levels= c("Leg1", "Leg2", "Leg3"))
  table(loaded_leg_w$LegGroup)
  
# Load the eigenvalues as a vector.
  eigen_loaded <- read.table("Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_WEIGHTED_eigen.txt", header=T)

# Make a vector that contains the variance explained.
  eigen_loaded_vec <- eigen_loaded[, 2]
  
# ---------------------------------------------------------------------------------------------------------------
# Save Axes 1 & 2, 1 & 3, 2 & 3, 3 & 4, 2 & 4 biplots with and without ellipses with specified confidence interval.
# The reults are saved with filenames with the specified "prefix_AxisXY.pdf" or "prefix_AxisXY_ellipses.pdf".
# You need to supply the same number of colors in the order of the factor level to be used. 
# dot.colors are for datapoints, and ellipses.colors are for ellipses outlines. 
  PlotAxis1to4ByFactor(axis.meta.df    = loaded_leg_w, 
                       factor.to.color = "LegGroup", 
                       eigen.vector    = eigen_percent_w ,
                       dot.colors      = c("steelblue3", "yellow", "green"), 
                       ellipses.colors = c("steelblue3", "gold3", "green"),  
                       ellipses.cflevel = 0.95,
                       out.prefix = "Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_WEIGHTED"
                       )

# ---------------------------------------------------------------------------------------------------------------
# The GLU_index groups look different. Use beta-diversity and adonis tests to see
# if they are actually distinct from one another.

# Generate a weighted unifrac distance matrix.
  dist_matrix_w <- phyloseq::distance(phyfoods, method = "wunifrac") # weighted
  
# Dispersion test and plot
# vegan::betadisper computes centeroids and distance of each datapoint from it. 
  dispr_w <- vegan::betadisper(d=dist_matrix_w, phyloseq::sample_data(phyfoods)$LegGroup)

# Show the centroids and dispersion of each group. 
  plot(dispr_w)
 
# Use dispr to do a permutation test for homogeneity of multivariate dispersion
# If p>0.05, the dispersion of each group are not different, and the assumption for adonis is met.
  vegan::permutest(dispr_w, perm = 5000)
  
# Use adonis to test whether there is a difference between groups' composition. 
  # i.e., composition among groups (food they consumed) is similar or not.
  vegan::adonis(dist_matrix_w ~ phyloseq::sample_data(phyfoods)$LegGroup, permutations = 5000)

# If overall adonis is significant, you can run pairwise adonis to see which group pairs are different.
  pairwise.adonis(dist_matrix_w, phyloseq::sample_data(phyfoods)$LegGroup, perm = 5000)  
  

# ===============================================================================================================
# Use your phyloseq object and perform ordination - UNweighted
# ===============================================================================================================
  
# Perform Principal Coordinate Analysis (PCoA) with UNweighted unifrac distance of your food data.
# This may take a few minutes depending on your data size.
# e.g. a large phyloseq object (7.9 MB) takes ~ 1 min. 
  ordinated_u <- phyloseq::ordinate(phyfoods, method="PCoA", distance="unifrac", weighted=FALSE)
  
# Save the percent variance explained by the axes as a vector to use in plots.  
  eigen_percent_u <- ordinated_u$values$Relative_eig
  
# Save the percent variance explained as a txt file.
  Eigen(eigen.input = eigen_percent_u, 
        output.fn="Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_UNweighted_eigen.txt")
  
# ===============================================================================================================
# Plot your ordination results - UNweighted
# ===============================================================================================================

# Merge the first n axes to the metadata and save it as a txt file. 
# The merged dataframe, 'meta_usersdf', will be used for plotting.
  MergeAxesAndMetadata_NHANES(ord.object= ordinated_u, number.of.axes= 10, meta.data= demog_leg_red, 
                              output.fn= "Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_UNweighted_meta_users.txt")
  View(MergeAxesAndMetadata_NHANES)
# Load the output again for plotting.
  loaded_leg_u <- read.table("Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_UNweighted_meta_users.txt",
                             sep="\t", header=T)  

# Convert the LegGroup as a factor to plot it in order.
  loaded_leg_u$LegGroup <- factor(loaded_leg_u$LegGroup, levels = c("Leg1", "Leg2", "Leg3"))

# Take a look at meta_usersdf_loaded. 
  head(loaded_leg_u, 2)
  
# ---------------------------------------------------------------------------------------------------------------
# Save Axes 1 & 2, 1 & 3, 2 & 3, 3 & 4, 2 & 4 biplots with and without ellipses with specified confidence interval.
# The reults are saved with filenames with the specified "prefix_AxisXY.pdf" or "prefix_AxisXY_ellipses.pdf".
# You need to supply the same number of colors in the order of the factor level to be used. 
# dot.colors are for datapoints, and ellipses.colors are for ellipses outlines. 
# [NOTE} For UNweighted results, change the input, eigen vectors, and prefix names accordingly. 
  PlotAxis1to4ByFactor(axis.meta.df    = loaded_leg_u, 
                       factor.to.color = "LegGroup", 
                       eigen.vector    = eigen_percent_u ,
                       dot.colors      = c("steelblue3", "yellow", "lawngreen"), 
                       ellipses.colors = c("steelblue3", "gold3", "green3"),  
                       ellipses.cflevel = 0.95,
                       out.prefix = "Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_UNweighted"
  )

# ---------------------------------------------------------------------------------------------------------------
# Use beta-diversity and adonis tests to see if they are they actually distinct from one another.

# Generate an UNweighted unifrac distance matrix.
  dist_matrix_u <- phyloseq::distance(phyfoods, method="unifrac")  # UNweighted
  
# Dispersion test and plot
  # vegan::betadisper computes centeroids and distance of each datapoint from it. 
  dispr_u <- vegan::betadisper(dist_matrix_u, phyloseq::sample_data(phyfoods)$LegGroup)
  
# Can show the centroids and dispersion of each group. 
  plot(dispr_u)
  
# Use dispr to do a permutation test for homogeneity of multivariate dispersion.
  vegan::permutest(dispr_u)
  # If p>0.05, the dispersion of each group are not different, and the assumption for adonis is met.
  
# Use adonis to test whether there is a difference between groups' composition. 
  # i.e., composition among groups (food they consumed) is similar or not.
  vegan::adonis(dist_matrix_u ~ phyloseq::sample_data(phyfoods)$LegGroup, permutations = 5000) 
  
# If overall adonis is significant, you can run pairwise adonis to see which group pairs are different.
  pairwise.adonis(dist_matrix_u, phyloseq::sample_data(phyfoods)$LegGroup, perm = 5000)
  
# ===============================================================================================================
# Save unifrac distance (UNweighted or WEIGHTED) matrices 
# ===============================================================================================================

# Generate and save an WEIGHTED unifrac distance matrix of "Samples". 
  WeightedUnifracDis(input.phyloseq.obj = phyfoods, 
                     output.fn = "Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_WEIGHTED_uni_dis.txt")        

# ---------------------------------------------------------------------------------------------------------------
# Generate and save an UNweighted unifrac distance matrix of "Samples". 
  UnweightedUnifracDis(input.phyloseq.obj = phyfoods, 
                       output.fn = "Food_D12_FC_QC_demo_QCed_leg_ftc_3Lv_ord_UNweighted_uni_dis.txt")        

# ---------------------------------------------------------------------------------------------------------------
# Come back to the main directory.
  setwd(main_wd)  
  

  
  